// Curated emoji data and Lucide icon name arrays for the Elements tab

const EMOJI_DATA = {
    popular: [
        { emoji: '⭐', name: 'Star', keywords: ['star', 'favorite', 'rating'] },
        { emoji: '🔥', name: 'Fire', keywords: ['fire', 'hot', 'trending'] },
        { emoji: '❤️', name: 'Red Heart', keywords: ['heart', 'love', 'like'] },
        { emoji: '✨', name: 'Sparkles', keywords: ['sparkles', 'magic', 'new'] },
        { emoji: '🎉', name: 'Party Popper', keywords: ['party', 'celebrate', 'confetti'] },
        { emoji: '🚀', name: 'Rocket', keywords: ['rocket', 'launch', 'fast', 'speed'] },
        { emoji: '💡', name: 'Light Bulb', keywords: ['idea', 'bulb', 'light', 'tip'] },
        { emoji: '✅', name: 'Check Mark', keywords: ['check', 'done', 'complete', 'yes'] },
        { emoji: '🎯', name: 'Bullseye', keywords: ['target', 'goal', 'aim', 'bullseye'] },
        { emoji: '💪', name: 'Flexed Bicep', keywords: ['strong', 'muscle', 'power', 'flex'] },
        { emoji: '👑', name: 'Crown', keywords: ['crown', 'king', 'queen', 'royal', 'best'] },
        { emoji: '🏆', name: 'Trophy', keywords: ['trophy', 'winner', 'award', 'champion'] },
        { emoji: '💰', name: 'Money Bag', keywords: ['money', 'rich', 'dollar', 'finance'] },
        { emoji: '🎨', name: 'Artist Palette', keywords: ['art', 'paint', 'design', 'creative'] },
        { emoji: '📱', name: 'Mobile Phone', keywords: ['phone', 'mobile', 'smartphone', 'app'] },
        { emoji: '💻', name: 'Laptop', keywords: ['laptop', 'computer', 'work', 'code'] },
        { emoji: '🔒', name: 'Lock', keywords: ['lock', 'secure', 'private', 'safe'] },
        { emoji: '⚡', name: 'Lightning', keywords: ['lightning', 'fast', 'electric', 'power', 'zap'] },
        { emoji: '🌟', name: 'Glowing Star', keywords: ['star', 'glow', 'bright', 'shine'] },
        { emoji: '💎', name: 'Gem', keywords: ['gem', 'diamond', 'premium', 'jewel'] },
        { emoji: '🔔', name: 'Bell', keywords: ['bell', 'notification', 'alert', 'ring'] },
        { emoji: '📊', name: 'Bar Chart', keywords: ['chart', 'graph', 'stats', 'analytics'] },
        { emoji: '🎵', name: 'Musical Note', keywords: ['music', 'note', 'song', 'audio'] },
        { emoji: '📸', name: 'Camera Flash', keywords: ['camera', 'photo', 'picture', 'snap'] },
        { emoji: '🌈', name: 'Rainbow', keywords: ['rainbow', 'color', 'pride', 'beautiful'] },
        { emoji: '💬', name: 'Speech Bubble', keywords: ['speech', 'chat', 'message', 'talk'] },
        { emoji: '🛡️', name: 'Shield', keywords: ['shield', 'protect', 'defense', 'safe'] },
        { emoji: '🎁', name: 'Gift', keywords: ['gift', 'present', 'surprise', 'reward'] },
        { emoji: '🔑', name: 'Key', keywords: ['key', 'unlock', 'access', 'password'] },
        { emoji: '📈', name: 'Chart Up', keywords: ['growth', 'increase', 'trending', 'up'] },
        { emoji: '❌', name: 'Cross Mark', keywords: ['cross', 'no', 'wrong', 'delete', 'cancel'] },
        { emoji: '💯', name: 'Hundred', keywords: ['hundred', 'perfect', 'score', '100'] },
    ],
    smileys: [
        { emoji: '😀', name: 'Grinning', keywords: ['happy', 'smile', 'grin'] },
        { emoji: '😃', name: 'Smiley', keywords: ['happy', 'smile', 'joy'] },
        { emoji: '😄', name: 'Smile', keywords: ['happy', 'smile', 'glad'] },
        { emoji: '😁', name: 'Beaming', keywords: ['grin', 'happy', 'teeth'] },
        { emoji: '😆', name: 'Laughing', keywords: ['laugh', 'lol', 'happy'] },
        { emoji: '😅', name: 'Sweat Smile', keywords: ['sweat', 'nervous', 'relief'] },
        { emoji: '🤣', name: 'ROFL', keywords: ['rolling', 'laugh', 'lol'] },
        { emoji: '😂', name: 'Joy', keywords: ['tears', 'laugh', 'funny'] },
        { emoji: '🙂', name: 'Slight Smile', keywords: ['smile', 'okay', 'fine'] },
        { emoji: '😉', name: 'Wink', keywords: ['wink', 'flirt', 'playful'] },
        { emoji: '😊', name: 'Blush', keywords: ['blush', 'happy', 'warm'] },
        { emoji: '😇', name: 'Halo', keywords: ['angel', 'innocent', 'good'] },
        { emoji: '🥰', name: 'Love Face', keywords: ['love', 'hearts', 'adore'] },
        { emoji: '😍', name: 'Heart Eyes', keywords: ['love', 'heart', 'wow'] },
        { emoji: '🤩', name: 'Star Struck', keywords: ['stars', 'amazing', 'wow'] },
        { emoji: '😘', name: 'Kissing', keywords: ['kiss', 'love', 'muah'] },
        { emoji: '😎', name: 'Cool', keywords: ['cool', 'sunglasses', 'confident'] },
        { emoji: '🤔', name: 'Thinking', keywords: ['think', 'hmm', 'consider'] },
        { emoji: '🤗', name: 'Hugging', keywords: ['hug', 'warm', 'embrace'] },
        { emoji: '🤯', name: 'Mind Blown', keywords: ['mind', 'blown', 'explode', 'shocked'] },
        { emoji: '😱', name: 'Screaming', keywords: ['scream', 'shock', 'fear'] },
        { emoji: '🥳', name: 'Partying', keywords: ['party', 'celebrate', 'fun'] },
        { emoji: '😴', name: 'Sleeping', keywords: ['sleep', 'zzz', 'tired'] },
        { emoji: '🤫', name: 'Shushing', keywords: ['quiet', 'secret', 'shh'] },
        { emoji: '🫡', name: 'Saluting', keywords: ['salute', 'respect', 'sir'] },
        { emoji: '🤓', name: 'Nerd', keywords: ['nerd', 'smart', 'glasses'] },
        { emoji: '😈', name: 'Devil', keywords: ['devil', 'evil', 'imp', 'mischief'] },
        { emoji: '👻', name: 'Ghost', keywords: ['ghost', 'boo', 'spooky'] },
        { emoji: '🤖', name: 'Robot', keywords: ['robot', 'ai', 'machine'] },
        { emoji: '👽', name: 'Alien', keywords: ['alien', 'ufo', 'space'] },
    ],
    objects: [
        { emoji: '⌚', name: 'Watch', keywords: ['watch', 'time', 'wrist'] },
        { emoji: '📱', name: 'Phone', keywords: ['phone', 'mobile', 'cell'] },
        { emoji: '💻', name: 'Laptop', keywords: ['laptop', 'computer'] },
        { emoji: '⌨️', name: 'Keyboard', keywords: ['keyboard', 'type', 'input'] },
        { emoji: '🖥️', name: 'Desktop', keywords: ['desktop', 'monitor', 'screen'] },
        { emoji: '🖨️', name: 'Printer', keywords: ['printer', 'print'] },
        { emoji: '🖱️', name: 'Mouse', keywords: ['mouse', 'click', 'cursor'] },
        { emoji: '💿', name: 'CD', keywords: ['cd', 'disc', 'dvd'] },
        { emoji: '📷', name: 'Camera', keywords: ['camera', 'photo'] },
        { emoji: '🎥', name: 'Movie Camera', keywords: ['movie', 'film', 'video'] },
        { emoji: '📺', name: 'Television', keywords: ['tv', 'television', 'screen'] },
        { emoji: '📻', name: 'Radio', keywords: ['radio', 'audio', 'broadcast'] },
        { emoji: '🎙️', name: 'Microphone', keywords: ['microphone', 'podcast', 'record'] },
        { emoji: '🎧', name: 'Headphones', keywords: ['headphones', 'music', 'audio'] },
        { emoji: '🔋', name: 'Battery', keywords: ['battery', 'power', 'charge'] },
        { emoji: '🔌', name: 'Plug', keywords: ['plug', 'power', 'electric'] },
        { emoji: '💡', name: 'Bulb', keywords: ['bulb', 'idea', 'light'] },
        { emoji: '🔦', name: 'Flashlight', keywords: ['flashlight', 'torch', 'light'] },
        { emoji: '📦', name: 'Package', keywords: ['package', 'box', 'ship', 'delivery'] },
        { emoji: '✉️', name: 'Envelope', keywords: ['envelope', 'mail', 'email', 'letter'] },
        { emoji: '📋', name: 'Clipboard', keywords: ['clipboard', 'list', 'paste'] },
        { emoji: '📝', name: 'Memo', keywords: ['memo', 'note', 'write'] },
        { emoji: '📁', name: 'Folder', keywords: ['folder', 'file', 'directory'] },
        { emoji: '📅', name: 'Calendar', keywords: ['calendar', 'date', 'schedule'] },
        { emoji: '📌', name: 'Pushpin', keywords: ['pin', 'pushpin', 'location'] },
        { emoji: '📎', name: 'Paperclip', keywords: ['paperclip', 'attach', 'clip'] },
        { emoji: '✂️', name: 'Scissors', keywords: ['scissors', 'cut', 'trim'] },
        { emoji: '🔧', name: 'Wrench', keywords: ['wrench', 'tool', 'fix', 'settings'] },
        { emoji: '🔨', name: 'Hammer', keywords: ['hammer', 'tool', 'build'] },
        { emoji: '⚙️', name: 'Gear', keywords: ['gear', 'settings', 'cog', 'config'] },
        { emoji: '🧲', name: 'Magnet', keywords: ['magnet', 'attract'] },
        { emoji: '🧪', name: 'Test Tube', keywords: ['test', 'lab', 'science', 'experiment'] },
        { emoji: '💊', name: 'Pill', keywords: ['pill', 'medicine', 'health'] },
        { emoji: '🪙', name: 'Coin', keywords: ['coin', 'money', 'gold'] },
        { emoji: '💳', name: 'Credit Card', keywords: ['credit', 'card', 'payment', 'bank'] },
        { emoji: '🛒', name: 'Shopping Cart', keywords: ['cart', 'shopping', 'buy'] },
        { emoji: '🎮', name: 'Game Controller', keywords: ['game', 'controller', 'play', 'gaming'] },
        { emoji: '🕹️', name: 'Joystick', keywords: ['joystick', 'game', 'arcade'] },
        { emoji: '🧩', name: 'Puzzle', keywords: ['puzzle', 'piece', 'jigsaw'] },
    ],
    symbols: [
        { emoji: '❤️', name: 'Red Heart', keywords: ['heart', 'love', 'red'] },
        { emoji: '🧡', name: 'Orange Heart', keywords: ['heart', 'orange'] },
        { emoji: '💛', name: 'Yellow Heart', keywords: ['heart', 'yellow'] },
        { emoji: '💚', name: 'Green Heart', keywords: ['heart', 'green'] },
        { emoji: '💙', name: 'Blue Heart', keywords: ['heart', 'blue'] },
        { emoji: '💜', name: 'Purple Heart', keywords: ['heart', 'purple'] },
        { emoji: '🖤', name: 'Black Heart', keywords: ['heart', 'black'] },
        { emoji: '🤍', name: 'White Heart', keywords: ['heart', 'white'] },
        { emoji: '💔', name: 'Broken Heart', keywords: ['heart', 'broken', 'sad'] },
        { emoji: '♻️', name: 'Recycle', keywords: ['recycle', 'green', 'eco'] },
        { emoji: '⚠️', name: 'Warning', keywords: ['warning', 'alert', 'caution'] },
        { emoji: '🚫', name: 'Prohibited', keywords: ['no', 'prohibited', 'ban', 'forbidden'] },
        { emoji: '✅', name: 'Check', keywords: ['check', 'done', 'complete', 'approved'] },
        { emoji: '❌', name: 'Cross', keywords: ['cross', 'no', 'wrong', 'cancel'] },
        { emoji: '❓', name: 'Question', keywords: ['question', 'ask', 'help'] },
        { emoji: '❗', name: 'Exclamation', keywords: ['exclamation', 'alert', 'important'] },
        { emoji: '💲', name: 'Dollar', keywords: ['dollar', 'money', 'price'] },
        { emoji: '🔴', name: 'Red Circle', keywords: ['red', 'circle', 'dot'] },
        { emoji: '🟢', name: 'Green Circle', keywords: ['green', 'circle', 'dot', 'online'] },
        { emoji: '🔵', name: 'Blue Circle', keywords: ['blue', 'circle', 'dot'] },
        { emoji: '🟡', name: 'Yellow Circle', keywords: ['yellow', 'circle', 'dot'] },
        { emoji: '🟠', name: 'Orange Circle', keywords: ['orange', 'circle', 'dot'] },
        { emoji: '🟣', name: 'Purple Circle', keywords: ['purple', 'circle', 'dot'] },
        { emoji: '⬛', name: 'Black Square', keywords: ['black', 'square'] },
        { emoji: '⬜', name: 'White Square', keywords: ['white', 'square'] },
        { emoji: '🔶', name: 'Orange Diamond', keywords: ['orange', 'diamond'] },
        { emoji: '🔷', name: 'Blue Diamond', keywords: ['blue', 'diamond'] },
        { emoji: '▶️', name: 'Play', keywords: ['play', 'start', 'video'] },
        { emoji: '⏸️', name: 'Pause', keywords: ['pause', 'stop'] },
        { emoji: '⏩', name: 'Fast Forward', keywords: ['forward', 'fast', 'skip'] },
        { emoji: '🔀', name: 'Shuffle', keywords: ['shuffle', 'random', 'mix'] },
        { emoji: '🔁', name: 'Repeat', keywords: ['repeat', 'loop', 'cycle'] },
        { emoji: '➕', name: 'Plus', keywords: ['plus', 'add', 'new'] },
        { emoji: '➖', name: 'Minus', keywords: ['minus', 'subtract', 'remove'] },
        { emoji: '➡️', name: 'Right Arrow', keywords: ['arrow', 'right', 'next', 'forward'] },
        { emoji: '⬅️', name: 'Left Arrow', keywords: ['arrow', 'left', 'back'] },
        { emoji: '⬆️', name: 'Up Arrow', keywords: ['arrow', 'up'] },
        { emoji: '⬇️', name: 'Down Arrow', keywords: ['arrow', 'down'] },
        { emoji: '↗️', name: 'Up-Right Arrow', keywords: ['arrow', 'diagonal', 'growth'] },
        { emoji: '🔗', name: 'Link', keywords: ['link', 'chain', 'url'] },
        { emoji: '♾️', name: 'Infinity', keywords: ['infinity', 'forever', 'loop'] },
        { emoji: '©️', name: 'Copyright', keywords: ['copyright', 'legal'] },
        { emoji: '™️', name: 'Trademark', keywords: ['trademark', 'brand'] },
        { emoji: '®️', name: 'Registered', keywords: ['registered', 'brand'] },
    ],
    animals: [
        { emoji: '🐶', name: 'Dog', keywords: ['dog', 'puppy', 'pet'] },
        { emoji: '🐱', name: 'Cat', keywords: ['cat', 'kitten', 'pet'] },
        { emoji: '🐭', name: 'Mouse', keywords: ['mouse', 'rodent'] },
        { emoji: '🐹', name: 'Hamster', keywords: ['hamster', 'pet'] },
        { emoji: '🐰', name: 'Rabbit', keywords: ['rabbit', 'bunny'] },
        { emoji: '🦊', name: 'Fox', keywords: ['fox', 'clever'] },
        { emoji: '🐻', name: 'Bear', keywords: ['bear', 'teddy'] },
        { emoji: '🐼', name: 'Panda', keywords: ['panda', 'bamboo'] },
        { emoji: '🐨', name: 'Koala', keywords: ['koala', 'australia'] },
        { emoji: '🦁', name: 'Lion', keywords: ['lion', 'king', 'brave'] },
        { emoji: '🐯', name: 'Tiger', keywords: ['tiger', 'fierce'] },
        { emoji: '🐮', name: 'Cow', keywords: ['cow', 'milk', 'farm'] },
        { emoji: '🐷', name: 'Pig', keywords: ['pig', 'oink', 'farm'] },
        { emoji: '🐸', name: 'Frog', keywords: ['frog', 'toad'] },
        { emoji: '🐵', name: 'Monkey', keywords: ['monkey', 'ape'] },
        { emoji: '🐔', name: 'Chicken', keywords: ['chicken', 'hen', 'farm'] },
        { emoji: '🐧', name: 'Penguin', keywords: ['penguin', 'cold', 'ice'] },
        { emoji: '🐦', name: 'Bird', keywords: ['bird', 'tweet', 'fly'] },
        { emoji: '🦅', name: 'Eagle', keywords: ['eagle', 'bird', 'fly'] },
        { emoji: '🦋', name: 'Butterfly', keywords: ['butterfly', 'insect', 'beautiful'] },
        { emoji: '🐛', name: 'Bug', keywords: ['bug', 'insect', 'caterpillar'] },
        { emoji: '🐝', name: 'Bee', keywords: ['bee', 'honey', 'buzz'] },
        { emoji: '🐠', name: 'Fish', keywords: ['fish', 'tropical', 'sea'] },
        { emoji: '🐬', name: 'Dolphin', keywords: ['dolphin', 'sea', 'smart'] },
        { emoji: '🦄', name: 'Unicorn', keywords: ['unicorn', 'magic', 'fantasy'] },
        { emoji: '🐉', name: 'Dragon', keywords: ['dragon', 'fire', 'fantasy'] },
        { emoji: '🦈', name: 'Shark', keywords: ['shark', 'sea', 'danger'] },
        { emoji: '🐙', name: 'Octopus', keywords: ['octopus', 'sea', 'tentacles'] },
        { emoji: '🦉', name: 'Owl', keywords: ['owl', 'wise', 'night'] },
        { emoji: '🐺', name: 'Wolf', keywords: ['wolf', 'wild', 'howl'] },
    ],
    food: [
        { emoji: '🍎', name: 'Apple', keywords: ['apple', 'fruit', 'red'] },
        { emoji: '🍊', name: 'Orange', keywords: ['orange', 'fruit', 'citrus'] },
        { emoji: '🍋', name: 'Lemon', keywords: ['lemon', 'fruit', 'citrus', 'sour'] },
        { emoji: '🍌', name: 'Banana', keywords: ['banana', 'fruit', 'yellow'] },
        { emoji: '🍇', name: 'Grapes', keywords: ['grapes', 'fruit', 'wine'] },
        { emoji: '🍓', name: 'Strawberry', keywords: ['strawberry', 'fruit', 'berry'] },
        { emoji: '🍑', name: 'Peach', keywords: ['peach', 'fruit'] },
        { emoji: '🍒', name: 'Cherry', keywords: ['cherry', 'fruit', 'red'] },
        { emoji: '🥑', name: 'Avocado', keywords: ['avocado', 'guac', 'green'] },
        { emoji: '🌶️', name: 'Hot Pepper', keywords: ['pepper', 'hot', 'spicy'] },
        { emoji: '🍕', name: 'Pizza', keywords: ['pizza', 'food', 'slice'] },
        { emoji: '🍔', name: 'Burger', keywords: ['burger', 'hamburger', 'food'] },
        { emoji: '🍟', name: 'Fries', keywords: ['fries', 'chips', 'food'] },
        { emoji: '🌮', name: 'Taco', keywords: ['taco', 'food', 'mexican'] },
        { emoji: '🍩', name: 'Donut', keywords: ['donut', 'doughnut', 'sweet'] },
        { emoji: '🍪', name: 'Cookie', keywords: ['cookie', 'biscuit', 'sweet'] },
        { emoji: '🎂', name: 'Birthday Cake', keywords: ['cake', 'birthday', 'celebration'] },
        { emoji: '🍰', name: 'Shortcake', keywords: ['cake', 'dessert', 'sweet'] },
        { emoji: '🧁', name: 'Cupcake', keywords: ['cupcake', 'muffin', 'sweet'] },
        { emoji: '☕', name: 'Coffee', keywords: ['coffee', 'tea', 'drink', 'hot'] },
        { emoji: '🍵', name: 'Tea', keywords: ['tea', 'green', 'drink'] },
        { emoji: '🥤', name: 'Cup with Straw', keywords: ['drink', 'soda', 'cup'] },
        { emoji: '🍺', name: 'Beer', keywords: ['beer', 'drink', 'cheers'] },
        { emoji: '🍷', name: 'Wine', keywords: ['wine', 'drink', 'glass'] },
        { emoji: '🥂', name: 'Clinking Glasses', keywords: ['cheers', 'toast', 'celebrate'] },
        { emoji: '🧃', name: 'Juice Box', keywords: ['juice', 'drink', 'box'] },
    ],
    travel: [
        { emoji: '🌍', name: 'Globe Europe', keywords: ['globe', 'earth', 'world', 'europe'] },
        { emoji: '🌎', name: 'Globe Americas', keywords: ['globe', 'earth', 'world', 'america'] },
        { emoji: '🌏', name: 'Globe Asia', keywords: ['globe', 'earth', 'world', 'asia'] },
        { emoji: '🗺️', name: 'World Map', keywords: ['map', 'world', 'travel'] },
        { emoji: '🏠', name: 'House', keywords: ['house', 'home', 'building'] },
        { emoji: '🏢', name: 'Office', keywords: ['office', 'building', 'work'] },
        { emoji: '🏥', name: 'Hospital', keywords: ['hospital', 'medical', 'health'] },
        { emoji: '🏫', name: 'School', keywords: ['school', 'education', 'learn'] },
        { emoji: '🏛️', name: 'Classical Building', keywords: ['building', 'classical', 'museum'] },
        { emoji: '⛪', name: 'Church', keywords: ['church', 'religion', 'building'] },
        { emoji: '🗼', name: 'Tokyo Tower', keywords: ['tower', 'tokyo', 'japan'] },
        { emoji: '🗽', name: 'Statue of Liberty', keywords: ['liberty', 'statue', 'nyc'] },
        { emoji: '✈️', name: 'Airplane', keywords: ['airplane', 'plane', 'fly', 'travel'] },
        { emoji: '🚗', name: 'Car', keywords: ['car', 'auto', 'drive'] },
        { emoji: '🚕', name: 'Taxi', keywords: ['taxi', 'cab', 'ride'] },
        { emoji: '🚌', name: 'Bus', keywords: ['bus', 'transit', 'ride'] },
        { emoji: '🚂', name: 'Train', keywords: ['train', 'rail', 'locomotive'] },
        { emoji: '🚀', name: 'Rocket', keywords: ['rocket', 'space', 'launch'] },
        { emoji: '🛸', name: 'UFO', keywords: ['ufo', 'alien', 'flying saucer'] },
        { emoji: '⛵', name: 'Sailboat', keywords: ['sailboat', 'boat', 'sea'] },
        { emoji: '🏖️', name: 'Beach', keywords: ['beach', 'vacation', 'sand'] },
        { emoji: '🏔️', name: 'Mountain', keywords: ['mountain', 'snow', 'peak'] },
        { emoji: '🌋', name: 'Volcano', keywords: ['volcano', 'eruption', 'lava'] },
        { emoji: '🏕️', name: 'Camping', keywords: ['camping', 'tent', 'outdoor'] },
        { emoji: '🎡', name: 'Ferris Wheel', keywords: ['ferris', 'wheel', 'amusement'] },
        { emoji: '🌅', name: 'Sunrise', keywords: ['sunrise', 'morning', 'dawn'] },
        { emoji: '🌄', name: 'Sunrise Over Mountains', keywords: ['sunrise', 'mountain', 'morning'] },
        { emoji: '🌃', name: 'Night City', keywords: ['night', 'city', 'stars'] },
        { emoji: '🌙', name: 'Crescent Moon', keywords: ['moon', 'night', 'crescent'] },
        { emoji: '☀️', name: 'Sun', keywords: ['sun', 'sunny', 'bright', 'day'] },
        { emoji: '⛅', name: 'Partly Cloudy', keywords: ['cloud', 'sun', 'weather'] },
        { emoji: '🌊', name: 'Wave', keywords: ['wave', 'ocean', 'sea', 'water'] },
        { emoji: '❄️', name: 'Snowflake', keywords: ['snow', 'cold', 'winter', 'ice'] },
    ],
    flags: [
        { emoji: '🇺🇸', name: 'US', keywords: ['us', 'usa', 'america', 'united states'] },
        { emoji: '🇬🇧', name: 'UK', keywords: ['uk', 'britain', 'united kingdom', 'england'] },
        { emoji: '🇩🇪', name: 'Germany', keywords: ['germany', 'deutsch'] },
        { emoji: '🇫🇷', name: 'France', keywords: ['france', 'french'] },
        { emoji: '🇪🇸', name: 'Spain', keywords: ['spain', 'spanish'] },
        { emoji: '🇮🇹', name: 'Italy', keywords: ['italy', 'italian'] },
        { emoji: '🇯🇵', name: 'Japan', keywords: ['japan', 'japanese'] },
        { emoji: '🇰🇷', name: 'South Korea', keywords: ['korea', 'korean'] },
        { emoji: '🇨🇳', name: 'China', keywords: ['china', 'chinese'] },
        { emoji: '🇧🇷', name: 'Brazil', keywords: ['brazil', 'brazilian'] },
        { emoji: '🇮🇳', name: 'India', keywords: ['india', 'indian'] },
        { emoji: '🇷🇺', name: 'Russia', keywords: ['russia', 'russian'] },
        { emoji: '🇨🇦', name: 'Canada', keywords: ['canada', 'canadian'] },
        { emoji: '🇦🇺', name: 'Australia', keywords: ['australia', 'australian'] },
        { emoji: '🇲🇽', name: 'Mexico', keywords: ['mexico', 'mexican'] },
        { emoji: '🇳🇱', name: 'Netherlands', keywords: ['netherlands', 'dutch', 'holland'] },
        { emoji: '🇸🇪', name: 'Sweden', keywords: ['sweden', 'swedish'] },
        { emoji: '🇳🇴', name: 'Norway', keywords: ['norway', 'norwegian'] },
        { emoji: '🇩🇰', name: 'Denmark', keywords: ['denmark', 'danish'] },
        { emoji: '🇫🇮', name: 'Finland', keywords: ['finland', 'finnish'] },
        { emoji: '🇵🇱', name: 'Poland', keywords: ['poland', 'polish'] },
        { emoji: '🇵🇹', name: 'Portugal', keywords: ['portugal', 'portuguese'] },
        { emoji: '🇹🇷', name: 'Turkey', keywords: ['turkey', 'turkish'] },
        { emoji: '🇸🇦', name: 'Saudi Arabia', keywords: ['saudi', 'arabia'] },
        { emoji: '🇦🇪', name: 'UAE', keywords: ['uae', 'dubai', 'emirates'] },
        { emoji: '🇹🇭', name: 'Thailand', keywords: ['thailand', 'thai'] },
        { emoji: '🇻🇳', name: 'Vietnam', keywords: ['vietnam', 'vietnamese'] },
        { emoji: '🇮🇩', name: 'Indonesia', keywords: ['indonesia', 'indonesian'] },
        { emoji: '🇵🇭', name: 'Philippines', keywords: ['philippines', 'filipino'] },
        { emoji: '🇳🇬', name: 'Nigeria', keywords: ['nigeria', 'nigerian'] },
        { emoji: '🇿🇦', name: 'South Africa', keywords: ['south africa'] },
        { emoji: '🇦🇷', name: 'Argentina', keywords: ['argentina'] },
        { emoji: '🇨🇱', name: 'Chile', keywords: ['chile', 'chilean'] },
        { emoji: '🇨🇴', name: 'Colombia', keywords: ['colombia', 'colombian'] },
        { emoji: '🏴', name: 'Black Flag', keywords: ['flag', 'black'] },
        { emoji: '🏳️', name: 'White Flag', keywords: ['flag', 'white', 'surrender'] },
        { emoji: '🏁', name: 'Checkered Flag', keywords: ['flag', 'finish', 'race'] },
        { emoji: '🚩', name: 'Red Flag', keywords: ['flag', 'red', 'warning'] },
        { emoji: '🏳️‍🌈', name: 'Rainbow Flag', keywords: ['rainbow', 'pride', 'lgbtq'] },
    ]
};

// ~50 popular Lucide icon slugs
const LUCIDE_POPULAR = [
    'star', 'heart', 'home', 'search', 'settings', 'user', 'mail', 'phone',
    'camera', 'image', 'video', 'music', 'play', 'pause', 'volume-2',
    'bell', 'calendar', 'clock', 'map-pin', 'navigation',
    'download', 'upload', 'share-2', 'link', 'external-link',
    'check', 'x', 'plus', 'minus', 'arrow-right',
    'arrow-left', 'arrow-up', 'arrow-down', 'chevron-right', 'chevron-down',
    'eye', 'eye-off', 'lock', 'unlock', 'shield',
    'zap', 'sun', 'moon', 'cloud', 'globe',
    'gift', 'shopping-cart', 'credit-card', 'trophy', 'target',
    'bookmark', 'flag', 'tag', 'folder', 'file-text'
];

// Full Lucide icon set (~1671 slugs)
const LUCIDE_ALL = [
    'accessibility','activity','air-vent','airplay','alarm-check','alarm-clock-check','alarm-clock-minus','alarm-clock-off','alarm-clock-plus','alarm-clock',
    'album','alert-circle','alert-octagon','alert-triangle','align-center-horizontal','align-center-vertical','align-center','align-end-horizontal','align-end-vertical','align-horizontal-distribute-center',
    'align-horizontal-distribute-end','align-horizontal-distribute-start','align-horizontal-justify-center','align-horizontal-justify-end','align-horizontal-justify-start','align-horizontal-space-around','align-horizontal-space-between','align-justify','align-left','align-right',
    'align-start-horizontal','align-start-vertical','align-vertical-distribute-center','align-vertical-distribute-end','align-vertical-distribute-start','align-vertical-justify-center','align-vertical-justify-end','align-vertical-justify-start','align-vertical-space-around','align-vertical-space-between',
    'anchor','angry','annoyed','antenna','aperture','app-window','apple','archive-restore','archive','area-chart',
    'armchair','arrow-big-down-dash','arrow-big-down','arrow-big-left-dash','arrow-big-left','arrow-big-right-dash','arrow-big-right','arrow-big-up-dash','arrow-big-up','arrow-down-01',
    'arrow-down-10','arrow-down-az','arrow-down-circle','arrow-down-from-line','arrow-down-left-from-circle','arrow-down-left','arrow-down-narrow-wide','arrow-down-right-from-circle','arrow-down-right','arrow-down-to-dot',
    'arrow-down-to-line','arrow-down-up','arrow-down-wide-narrow','arrow-down-za','arrow-down','arrow-left-circle','arrow-left-from-line','arrow-left-right','arrow-left-to-line','arrow-left',
    'arrow-right-circle','arrow-right-from-line','arrow-right-left','arrow-right-to-line','arrow-right','arrow-up-01','arrow-up-10','arrow-up-az','arrow-up-circle','arrow-up-down',
    'arrow-up-from-dot','arrow-up-from-line','arrow-up-left-from-circle','arrow-up-left','arrow-up-narrow-wide','arrow-up-right-from-circle','arrow-up-right','arrow-up-to-line','arrow-up-wide-narrow','arrow-up-za',
    'arrow-up','arrows-up-from-line','asterisk','at-sign','atom','audio-lines','audio-waveform','award',
    'axe','axis-3d','baby','backpack','badge-alert','badge-cent','badge-check','badge-dollar-sign','badge-euro','badge-help',
    'badge-indian-rupee','badge-info','badge-japanese-yen','badge-minus','badge-percent','badge-plus','badge-pound-sterling','badge-russian-ruble','badge-swiss-franc','badge-x',
    'badge','baggage-claim','ban','banana','banknote','bar-chart-2','bar-chart-3','bar-chart-4','bar-chart-big','bar-chart-horizontal-big',
    'bar-chart-horizontal','bar-chart','baseline','bath','battery-charging','battery-full','battery-low','battery-medium','battery-warning','battery',
    'beaker','bean-off','bean','bed-double','bed-single','bed','beef','beer','bell-dot','bell-minus',
    'bell-off','bell-plus','bell-ring','bell','bike','binary','biohazard','bird','bitcoin','blend',
    'blinds','blocks','bluetooth-connected','bluetooth-off','bluetooth-searching','bluetooth','bold','bolt','bomb','bone',
    'book-copy','book-down','book-heart','book-key','book-lock','book-marked','book-minus','book-open-check','book-open-text','book-open',
    'book-plus','book-text','book-type','book-up-2','book-up','book-user','book-x','book','bookmark-check','bookmark-minus',
    'bookmark-plus','bookmark-x','bookmark','boom-box','bot','box-select','box','boxes','braces','brackets',
    'brain-circuit','brain-cog','brain','brick-wall','briefcase','bring-to-front','brush','bug-off','bug-play','bug',
    'building-2','building','bus-front','bus','cable-car','cable','cake-slice','cake','calculator','calendar-check-2',
    'calendar-check','calendar-clock','calendar-days','calendar-heart','calendar-minus','calendar-off','calendar-plus','calendar-range','calendar-search','calendar-x',
    'calendar','camera-off','camera','candlestick-chart','candy-off','candy','car-front','car-taxi-front','car','carrot',
    'case-lower','case-sensitive','case-upper','cast','castle','cat','check-check','check-circle-2','check-circle','check-square',
    'check','chef-hat','cherry','chevron-down-circle','chevron-down-square','chevron-down','chevron-first','chevron-last','chevron-left-circle','chevron-left-square',
    'chevron-left','chevron-right-circle','chevron-right-square','chevron-right','chevron-up-circle','chevron-up-square','chevron-up','chevrons-down-up','chevrons-down','chevrons-left-right',
    'chevrons-left','chevrons-right-left','chevrons-right','chevrons-up-down','chevrons-up','chrome','church','cigarette-off','cigarette','circle-dashed',
    'circle-dollar-sign','circle-dot','circle-ellipsis','circle-equal','circle-off','circle-slash-2','circle-slash','circle-user','circle','circuit-board',
    'citrus','clapperboard','clipboard-check','clipboard-copy','clipboard-edit','clipboard-list','clipboard-paste','clipboard-signature','clipboard-type','clipboard-x',
    'clipboard','clock-1','clock-10','clock-11','clock-12','clock-2','clock-3','clock-4','clock-5','clock-6',
    'clock-7','clock-8','clock-9','clock','cloud-cog','cloud-drizzle','cloud-fog','cloud-hail','cloud-lightning','cloud-moon-rain',
    'cloud-moon','cloud-off','cloud-rain-wind','cloud-rain','cloud-snow','cloud-sun-rain','cloud-sun','cloud','clover','club',
    'code-2','code','codepen','codesandbox','coffee','cog','coins','columns','combine','command',
    'compass','component','computer','concierge-bell','cone','construction','contact-2','contact','container','contrast',
    'cookie','copy-check','copy-minus','copy-plus','copy-slash','copy-x','copy','copyleft','corner-down-left','corner-down-right',
    'corner-left-down','corner-left-up','corner-right-down','corner-right-up','corner-up-left','corner-up-right','cpu','creative-commons','credit-card','croissant',
    'crop','cross','crosshair','crown','cuboid','cup-soda','currency','database-backup','database-zap','database',
    'delete','dessert','diamond','dice-1','dice-2','dice-3','dice-4','dice-5','dice-6','dices',
    'diff','disc-2','disc-3','disc','divide-circle','divide-square','divide','dna-off','dna','dog',
    'dollar-sign','donut','door-closed','door-open','dot','download-cloud','download','drafting-compass','drama','dribbble',
    'droplet','droplets','drum','drumstick','dumbbell',
    'ear-off','ear','edit-2','edit-3','edit','egg-fried','egg-off','egg','equal-not','equal',
    'eraser','euro','expand','external-link','eye-off','eye',
    'facebook','factory','fan','fast-forward','feather','fence','ferris-wheel','figma','file-archive','file-audio-2',
    'file-audio','file-axis-3d','file-badge-2','file-badge','file-bar-chart-2','file-bar-chart','file-box','file-check-2','file-check','file-clock',
    'file-code-2','file-code','file-cog','file-diff','file-digit','file-down','file-edit','file-heart','file-image','file-input',
    'file-json-2','file-json','file-key-2','file-key','file-line-chart','file-lock-2','file-lock','file-minus-2','file-minus','file-output',
    'file-pie-chart','file-plus-2','file-plus','file-question','file-scan','file-search-2','file-search','file-signature','file-spreadsheet','file-stack',
    'file-symlink','file-terminal','file-text','file-type-2','file-type','file-up','file-video-2','file-video','file-volume-2','file-volume',
    'file-warning','file-x-2','file-x','file','files','film','filter-x','filter','fingerprint','fire-extinguisher',
    'fish-off','fish-symbol','fish','flag-off','flag-triangle-left','flag-triangle-right','flag','flame-kindling','flame','flashlight-off',
    'flashlight','flask-conical-off','flask-conical','flask-round','flip-horizontal-2','flip-horizontal','flip-vertical-2','flip-vertical','flower-2','flower',
    'focus','fold-horizontal','fold-vertical','folder-archive','folder-check','folder-clock','folder-closed','folder-cog','folder-dot','folder-down',
    'folder-edit','folder-git-2','folder-git','folder-heart','folder-input','folder-kanban','folder-key','folder-lock','folder-minus','folder-open-dot',
    'folder-open','folder-output','folder-plus','folder-root','folder-search-2','folder-search','folder-symlink','folder-sync','folder-tree','folder-up',
    'folder-x','folder','folders','footprints','forklift','form-input','forward','frame','framer','frown',
    'fuel','fullscreen','function-square',
    'gallery-horizontal-end','gallery-horizontal','gallery-thumbnails','gallery-vertical-end','gallery-vertical','gamepad-2','gamepad','gauge-circle','gauge','gavel',
    'gem','ghost','gift','git-branch-plus','git-branch','git-commit-horizontal','git-commit-vertical','git-compare-arrows','git-compare','git-fork',
    'git-graph','git-merge','git-pull-request-arrow','git-pull-request-closed','git-pull-request-create','git-pull-request-draft','git-pull-request','github','gitlab','glass-water',
    'glasses','globe-2','globe','goal','grab','graduation-cap','grape','grid-2x2','grid-3x3','grip-horizontal',
    'grip-vertical','grip','group','guitar',
    'hammer','hand-coins','hand-heart','hand-helping','hand-metal','hand','handshake','hard-drive-download','hard-drive-upload','hard-drive',
    'hard-hat','hash','haze','hdmi-port','heading-1','heading-2','heading-3','heading-4','heading-5','heading-6',
    'heading','headphones','heart-crack','heart-handshake','heart-off','heart-pulse','heart','heater','helping-hand','hexagon',
    'highlighter','history','hop-off','hop','hospital','hotel','hourglass','house-plus','house',
    'ice-cream-2','ice-cream','image-down','image-minus','image-off','image-plus','image','import','inbox','indent',
    'indian-rupee','infinity','info','inspect','instagram','italic',
    'japanese-yen','joystick',
    'kanban-square-dashed','kanban-square','kanban','key-round','key-square','key','keyboard','lamp-ceiling','lamp-desk','lamp-floor',
    'lamp-wall-down','lamp-wall-up','lamp','landmark','languages','laptop-2','laptop','lasso-select','lasso','laugh',
    'layers-2','layers-3','layers','layout-dashboard','layout-grid','layout-list','layout-panel-left','layout-panel-top','layout-template','leaf',
    'library-big','library','life-buoy','ligature','lightbulb-off','lightbulb','line-chart','link-2-off','link-2','link',
    'linkedin','list-checks','list-collapse','list-end','list-filter','list-minus','list-music','list-ordered','list-plus','list-restart',
    'list-start','list-todo','list-tree','list-video','list-x','list','loader-2','loader','locate-fixed','locate-off',
    'locate','lock','log-in','log-out','lollipop','luggage',
    'magnet','mail-check','mail-minus','mail-open','mail-plus','mail-question','mail-search','mail-warning','mail-x','mail',
    'mailbox','map-pin-off','map-pin','map','martini','maximize-2','maximize','medal','megaphone','meh',
    'memory-stick','menu-square','menu','merge','message-circle','message-square-dashed','message-square-plus','message-square','messages-square','mic-2',
    'mic-off','mic','microscope','microwave','milestone','milk-off','milk','minimize-2','minimize','minus-circle',
    'minus-square','minus','monitor-check','monitor-dot','monitor-down','monitor-off','monitor-pause','monitor-play','monitor-smartphone','monitor-speaker',
    'monitor-stop','monitor-up','monitor-x','monitor','moon-star','moon','more-horizontal','more-vertical','mountain-snow','mountain',
    'mouse-pointer-2','mouse-pointer-click','mouse-pointer','mouse','move-3d','move-diagonal-2','move-diagonal','move-down-left','move-down-right','move-down',
    'move-horizontal','move-left','move-right','move-up-left','move-up-right','move-up','move-vertical','move','music-2','music-3',
    'music-4','music',
    'navigation-2-off','navigation-2','navigation-off','navigation','network','newspaper','nfc','notebook-pen','notebook-tabs','notebook',
    'nut-off','nut',
    'octagon','option','orbit','outdent',
    'package-2','package-check','package-minus','package-open','package-plus','package-search','package-x','package','paint-bucket','paintbrush-2',
    'paintbrush','palette','palmtree','panel-bottom-close',
    'panel-bottom-dashed','panel-bottom-open','panel-bottom','panel-left-close','panel-left-dashed','panel-left-open','panel-left','panel-right-close','panel-right-dashed','panel-right-open',
    'panel-right','panel-top-close','panel-top-dashed','panel-top-open','panel-top','paperclip','parentheses','parking-circle-off','parking-circle','parking-meter',
    'parking-square-off','parking-square','party-popper','pause-circle','pause-octagon','pause','paw-print','pc-case','pen-line','pen-square',
    'pen-tool','pen','pencil-line','pencil-ruler','pencil','pentagon','percent','person-standing','phone-call','phone-forwarded',
    'phone-incoming','phone-missed','phone-off','phone-outgoing','phone','pi-square','pi','picture-in-picture-2','picture-in-picture','pie-chart',
    'piggy-bank','pilcrow','pill','pin-off','pin','pipette','pizza','plane-landing','plane-takeoff','plane',
    'play-circle','play-square','play','plug-2','plug-zap','plug','plus-circle','plus-square','plus','pocket-knife',
    'pocket','podcast','pointer','popcorn','popsicle','pound-sterling','power-off','power','presentation','printer',
    'projector','puzzle','pyramid',
    'qr-code','quote',
    'rabbit','radar','radiation','radio-receiver','radio-tower','radio','rail-symbol','rainbow','rat','ratio',
    'receipt','rectangle-horizontal','rectangle-vertical','recycle','redo-2','redo-dot','redo','refresh-ccw-dot','refresh-ccw','refresh-cw-off',
    'refresh-cw','refrigerator','regex','remove-formatting','repeat-1','repeat-2','repeat','replace-all','replace','reply-all',
    'reply','rewind','ribbon','rocket','rocking-chair','roller-coaster','rotate-3d','rotate-ccw','rotate-cw','route-off',
    'route','router','rows-2','rows-3','rows-4','rss','ruler','russian-ruble',
    'sailboat','salad','sandwich','satellite-dish','satellite','save-all','save','scale-3d','scale','scaling',
    'scan-barcode','scan-eye','scan-face','scan-line','scan-search','scan-text','scan','scatter-chart','school-2','school',
    'scissors-line-dashed','scissors-square-dashed-bottom','scissors-square','scissors','screen-share-off','screen-share','scroll-text','scroll','search-check','search-code',
    'search-slash','search-x','search','send-horizontal','send-to-back','send','separator-horizontal','separator-vertical','server-cog','server-crash',
    'server-off','server','settings-2','settings','shapes','share-2','share','sheet','shell','shield-alert',
    'shield-ban','shield-check','shield-ellipsis','shield-half','shield-minus','shield-off','shield-plus','shield-question','shield-x','shield',
    'ship-wheel','ship','shirt','shopping-bag','shopping-basket','shopping-cart','shovel','shower-head','shrink','shrub',
    'shuffle','sigma','signal-high','signal-low','signal-medium','signal-zero','signal','signpost-big','signpost','siren',
    'skip-back','skip-forward','skull','slack','slash','slice','sliders-horizontal','sliders','smartphone-charging','smartphone-nfc',
    'smartphone','smile-plus','smile','snail','snowflake','sofa','soup','space','spade','sparkle',
    'sparkles','speaker','speech','spell-check-2','spell-check','spline','split-square-horizontal','split-square-vertical','split','spray-can',
    'sprout','square-asterisk','square-code','square-dashed-bottom-code','square-dashed-bottom','square-dot','square-equal','square-gantt-chart','square-kanban','square-library',
    'square-menu','square-mouse-pointer','square-parking-off','square-parking','square-pen','square-percent','square-pi','square-pilcrow','square-play','square-plus',
    'square-power','square-radical','square-scissors','square-sigma','square-slash','square-split-horizontal','square-split-vertical','square-stack','square-terminal','square-user-round',
    'square-user','square-x','square','squircle','squirrel','stamp','star-half','star-off','star','step-back',
    'step-forward','stethoscope','sticker','sticky-note','store','stretch-horizontal','stretch-vertical','strikethrough','subscript','sun-dim',
    'sun-medium','sun-moon','sun-snow','sun','sunrise','sunset','superscript','swatch-book','swiss-franc','switch-camera',
    'sword','swords','syringe',
    'table-2','table-properties','table','tablet-smartphone','tablet','tablets','tag','tags','tally-1','tally-2',
    'tally-3','tally-4','tally-5','tangent','target','tent-tree','tent','terminal-square','terminal','test-tube-2',
    'test-tube-diagonal','test-tube','test-tubes','text-cursor-input','text-cursor','text-quote','text-search','text-select','text','theater',
    'thermometer-snowflake','thermometer-sun','thermometer','thumbs-down','thumbs-up','ticket','timer-off','timer-reset','timer','toggle-left',
    'toggle-right','tornado','torus','touchpad-off','touchpad','tower-control','toy-brick','tractor','traffic-cone','train-front-tunnel',
    'train-front','train-track','tram-front','trash-2','trash','tree-deciduous','tree-pine','trees','trending-down','trending-up',
    'triangle-right','triangle','trophy','truck','turtle','tv-2','tv','twitch','twitter','type',
    'umbrella-off','umbrella','underline','undo-2','undo-dot','undo','ungroup','university','unlink-2','unlink',
    'unlock','unplug','upload-cloud','upload','usb','user-check','user-cog','user-minus','user-plus','user-round-check',
    'user-round-cog','user-round-minus','user-round-plus','user-round-search','user-round-x','user-round','user-search','user-x','user','users-round',
    'users','utensils-crossed','utensils','utility-pole',
    'variable','vault','vegan','venetian-mask','vibrate-off','vibrate','video-off','video','videotape','view',
    'voicemail','volume-1','volume-2','volume-x','volume','vote',
    'wallet-cards','wallet-minimal','wallet','wallpaper','wand-2','wand','warehouse','washing-machine','watch','waves',
    'waypoints','webcam','webhook','weight','wheat-off','wheat','whole-word','wifi-off','wifi','wind',
    'wine-off','wine','workflow','worm','wrap-text','wrench',
    'x-circle','x-octagon','x-square','x',
    'youtube',
    'zap-off','zap','zoom-in','zoom-out'
];
